# Generated by Django 4.2.7 on 2026-01-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(choices=[('samsung', 'Samsung'), ('apple', 'Apple'), ('google', 'Google'), ('oneplus', 'OnePlus'), ('xiaomi', 'Xiaomi'), ('huawei', 'Huawei'), ('sony', 'Sony'), ('lg', 'LG'), ('motorola', 'Motorola'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
